# NB: don't set `language: haskell` here

# See also https://github.com/hvr/multi-ghc-travis for more information

env:
 - MYSETUP=7.6.3.gtk
 - MYSETUP=7.6.3.vty
 - MYSETUP=7.8.4.gtk
 - MYSETUP=7.8.4.vty
# - MYSETUP=7.10.1.gtk
# - MYSETUP=7.10.1.vty
 - MYSETUP=2014.2.0.0.gtk
 - MYSETUP=2014.2.0.0.vty
 - MYSETUP=2013.2.0.0.gtk
 - MYSETUP=2013.2.0.0.vty
 - MYSETUP=2012.4.0.0.gtk
 - MYSETUP=2012.4.0.0.vty

# Note: the distinction between `before_install` and `install` is not
#       important.
before_install:
 - case "$MYSETUP" in
    "") ;;

    "7.6.3.gtk")
      export GHCVER=7.6.3 ;
      export CABALVER=1.18 ;
      export GTKVTY=gtk ;;

    "7.6.3.vty")
      export GHCVER=7.6.3 ;
      export CABALVER=1.18 ;
      export GTKVTY=vty ;;

    "7.8.4.gtk")
      export GHCVER=7.8.4 ;
      export CABALVER=1.18 ;
      export GTKVTY=gtk ;;

    "7.8.4.vty")
      export GHCVER=7.8.4 ;
      export CABALVER=1.18 ;
      export GTKVTY=vty ;;

    "7.10.1.gtk")
      export GHCVER=7.10.1 ;
      export CABALVER=1.22 ;
      export GTKVTY=gtk ;;

    "7.10.1.vty")
      export GHCVER=7.10.1 ;
      export CABALVER=1.22 ;
      export GTKVTY=vty ;;

    "2014.2.0.0.gtk")
      export GHCVER=7.8.3 ;
      export CABALVER=1.18 ;
      export GTKVTY=gtk ;
      echo "constraints:async==2.0.1.5,attoparsec==0.10.4.0,case-insensitive==1.1.0.3,fgl==5.5.0.1,GLUT==2.5.1.1,GLURaw==1.4.0.1,haskell-src==1.0.1.6,hashable==1.2.2.0,html==1.0.1.2,HTTP==4000.2.10,HUnit==1.2.5.2,mtl==2.1.3.1,network==2.4.2.3,OpenGL==2.9.2.0,OpenGLRaw==1.5.0.0,parallel==3.2.0.4,parsec==3.1.5,primitive==0.5.2.1,QuickCheck==2.6,random==1.0.1.1,regex-base==0.93.2,regex-compat==0.95.1,regex-posix==0.95.2,split==0.2.2,stm==2.4.2,syb==0.4.1,text==1.1.0.0,transformers==0.3.0.0,unordered-containers==0.2.4.0,vector==0.10.9.1,xhtml==3000.2.1,zlib==0.5.4.1" > cabal.config ;;

    "2013.2.0.0.gtk")
      export GHCVER=7.6.3 ;
      export CABALVER=1.18 ;
      export GTKVTY=gtk ;
      echo "constraints:async==2.0.1.4,attoparsec==0.10.4.0,case-insensitive==1.0.0.1,cgi==3001.1.7.5,fgl==5.4.2.4,GLUT==2.4.0.0,GLURaw==1.3.0.0,haskell-src==1.0.1.5,html==1.0.1.2,HTTP==4000.2.8,HUnit==1.2.5.2,mtl==2.1.2,network==2.4.1.2,OpenGL==2.8.0.0,OpenGLRaw==1.3.0.0,parallel==3.2.0.3,parsec==3.1.3,QuickCheck==2.6,random==1.0.1.1,regex-base==0.93.2,regex-compat==0.95.1,regex-posix==0.95.2,split==0.2.2,stm==2.4.2,syb==0.4.0,text==0.11.3.1,transformers==0.3.0.0,unordered-containers==0.2.3.0,vector==0.10.0.1,xhtml==3000.2.1,zlib==0.5.4.1" > cabal.config ;;

    "2012.4.0.0.gtk")
      export GHCVER=7.6.2 ;
      export CABALVER=1.18 ;
      export GTKVTY=gtk ;
      echo "constraints:async==2.0.1.3,cgi==3001.1.7.4,fgl==5.4.2.4,GLUT==2.1.2.1,haskell-src==1.0.1.5,html==1.0.1.2,HTTP==4000.2.5,HUnit==1.2.5.1,mtl==2.1.2,network==2.3.1.0,OpenGL==2.2.3.1,parallel==3.2.0.3,parsec==3.1.3,QuickCheck==2.5.1.1,random==1.0.1.1,regex-base==0.93.2,regex-compat==0.95.1,regex-posix==0.95.2,split==0.2.1.1,stm==2.4,syb==0.3.7,text==0.11.3.1,transformers==0.3.0.0,vector==0.10.0.1,xhtml==3000.2.1,zlib==0.5.4.0" > cabal.config ;;

    "2014.2.0.0.vty")
      export GHCVER=7.8.3 ;
      export CABALVER=1.18 ;
      export GTKVTY=vty ;
      echo "constraints:async==2.0.1.5,attoparsec==0.10.4.0,case-insensitive==1.1.0.3,fgl==5.5.0.1,GLUT==2.5.1.1,GLURaw==1.4.0.1,haskell-src==1.0.1.6,hashable==1.2.2.0,html==1.0.1.2,HTTP==4000.2.10,HUnit==1.2.5.2,mtl==2.1.3.1,network==2.4.2.3,OpenGL==2.9.2.0,OpenGLRaw==1.5.0.0,parallel==3.2.0.4,parsec==3.1.5,primitive==0.5.2.1,QuickCheck==2.6,random==1.0.1.1,regex-base==0.93.2,regex-compat==0.95.1,regex-posix==0.95.2,split==0.2.2,stm==2.4.2,syb==0.4.1,text==1.1.0.0,transformers==0.3.0.0,unordered-containers==0.2.4.0,vector==0.10.9.1,xhtml==3000.2.1,zlib==0.5.4.1" > cabal.config ;;

    "2013.2.0.0.vty")
      export GHCVER=7.6.3 ;
      export CABALVER=1.18 ;
      export GTKVTY=vty ;
      echo "constraints:async==2.0.1.4,attoparsec==0.10.4.0,case-insensitive==1.0.0.1,cgi==3001.1.7.5,fgl==5.4.2.4,GLUT==2.4.0.0,GLURaw==1.3.0.0,haskell-src==1.0.1.5,html==1.0.1.2,HTTP==4000.2.8,HUnit==1.2.5.2,mtl==2.1.2,network==2.4.1.2,OpenGL==2.8.0.0,OpenGLRaw==1.3.0.0,parallel==3.2.0.3,parsec==3.1.3,QuickCheck==2.6,random==1.0.1.1,regex-base==0.93.2,regex-compat==0.95.1,regex-posix==0.95.2,split==0.2.2,stm==2.4.2,syb==0.4.0,text==0.11.3.1,transformers==0.3.0.0,unordered-containers==0.2.3.0,vector==0.10.0.1,xhtml==3000.2.1,zlib==0.5.4.1" > cabal.config ;;

    "2012.4.0.0.vty")
      export GHCVER=7.6.2 ;
      export CABALVER=1.18 ;
      export GTKVTY=vty ;
      echo "constraints:async==2.0.1.3,cgi==3001.1.7.4,fgl==5.4.2.4,GLUT==2.1.2.1,haskell-src==1.0.1.5,html==1.0.1.2,HTTP==4000.2.5,HUnit==1.2.5.1,mtl==2.1.2,network==2.3.1.0,OpenGL==2.2.3.1,parallel==3.2.0.3,parsec==3.1.3,QuickCheck==2.5.1.1,random==1.0.1.1,regex-base==0.93.2,regex-compat==0.95.1,regex-posix==0.95.2,split==0.2.1.1,stm==2.4,syb==0.3.7,text==0.11.3.1,transformers==0.3.0.0,vector==0.10.0.1,xhtml==3000.2.1,zlib==0.5.4.0" > cabal.config ;;

    *)
      export GHCVER=unknown ;
      echo "unknown/invalid Haskell Platform requested" ;
      exit 1 ;;

   esac

 - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
 - travis_retry sudo apt-get update
 - travis_retry sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER
 - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH

install:
 - cabal --version
 - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
 - travis_retry cabal update

 - |
   if [ ${GHCVER%.*} = "7.6" ]; then
     travis_retry sudo apt-get install happy alex;
     if [ $GTKVTY = "vty" ]; then
       cabal install -j2 Cabal-1.18.0;
     fi;
   else
     travis_retry sudo apt-get install happy-1.19.4 alex-3.1.3;
     export PATH=/opt/alex/3.1.3/bin:/opt/happy/1.19.4/bin:$PATH;
   fi

# mine (7.6 struggles with -O2):
 - cd ..
 - git clone --depth=50 --branch=mikolaj git://github.com/LambdaHack/LambdaHack.git
 - if [ -f Allure/cabal.config ]; then cp Allure/cabal.config LambdaHack; fi
 - cd LambdaHack
 - |
   if [ $GTKVTY = "gtk" ]; then
     cabal install -j2 gtk2hs-buildtools;
     if [ ${GHCVER%.*} = "7.6" ]; then
       cabal install -j2 -frelease -O1 --only-dependencies --force-reinstalls;
       cabal configure -frelease -O1;
     else
       cabal install -j2 -frelease --only-dependencies --force-reinstalls;
       cabal configure -frelease;
     fi;
   else
     if [ ${GHCVER%.*} = "7.6" ]; then
       cabal install -fvty -j2 -f-release -O1 --only-dependencies --force-reinstalls;
       cabal configure -fvty -f-release -O1;
     else
       cabal install -fvty -j2 -f-release --only-dependencies --force-reinstalls;
       cabal configure -fvty -f-release;
     fi;
   fi
 - cabal build -j2
 - cabal copy
 - cabal register
 - cd ../Allure
 - cabal install -j2 -frelease --only-dependencies --force-reinstalls
 - cabal configure -frelease --enable-tests
 - cabal build -j2
 - cabal test

# Here starts the actual work to be performed for the package under
# test; any command which exits with a non-zero exit code causes the
# build to fail.
script:
 # tests that a source-distribution is correct; ignore -O2 warning
 - cabal check || true

 # tests that a source-distribution can be generated; ignore -O2 warning
 - cabal sdist || true

 # check that the generated source-distribution can be built & installed
 - export SRC_TGZ=$(cabal info . | awk '{print $2 ".tar.gz";exit}');
   cd dist/;
   if [ -f "$SRC_TGZ" ]; then
      if [ $GTKVTY = "gtk" ]; then
        cabal install -j2 "$SRC_TGZ";
      else
        cabal install -fvty -j2 "$SRC_TGZ";
      fi;
   else
      echo "expected '$SRC_TGZ' not found";
      exit 1;
   fi;
   cd ..

# mine:
 - |
   if [ ${GHCVER%.*} = "7.6" ]; then
     touch /tmp/stdtest.log;
     (make test-travis-long || (tail -n 200 /tmp/stdtest.log ; exit 77));
   else
     touch /tmp/stdtest.log;
     (make test-travis-long-no-safari || (tail -n 200 /tmp/stdtest.log ; exit 77));
   fi

# EOF
