language: haskell

install:
  - cabal install gtk2hs-buildtools
  - cabal install LambdaHack --enable-tests --reinstall --constraint="mtl>=2.1.2" --constraint="containers>=0.5.2.1" --constraint="template-haskell>=2.7.0.0" --constraint="text>=0.11.2.3"
  - cabal install --enable-tests --reinstall
