language: haskell

install:
  - cabal install gtk2hs-buildtools
  - cabal install LambdaHack ConfigFile regex-posix regex-compat gtk --force-reinstalls --reinstall --constraint="mtl>=2.1.2" --constraint="containers>=0.5.2.1" --constraint="template-haskell>=2.7.0.0" --constraint="text>=0.11.2.3" --solver=modular
  - cabal install --enable-tests --reinstall --solver=modular
