language: haskell

install:
  - cd ..
  - git clone --depth=50 --branch=mikolaj git://github.com/kosmikus/LambdaHack.git
  - cd LambdaHack
  - cabal install gtk2hs-buildtools
  - cabal install
  - cd ../Allure
  - cabal install --only-dependencies

script:
  - cabal install
  - make test-travis || (cat ~/.Allure/config.rules.dump ; tail -n 200 /tmp/stdtest.log ; exit 77)
  - cabal install Allure --reinstall
