environment:
  global:
    CABOPTS:  "--store-dir=C:\\SR --http-transport=plain-http"

cache:
- "C:\\SR"

install:
  - appveyor-retry choco install ghc --version 8.4.4 | grep -v '^Extracting the last GHC that works on Windows Vista'
  # breaks appveyor-retry: refreshenv
  - SET PATH=%APPDATA%\cabal\bin;C:\msys64\mingw64\bin;C:\msys64\usr\bin;C:\ProgramData\chocolatey\lib\ghc\tools\ghc-8.4.4\bin;C:\ProgramData\chocolatey\lib\cabal\tools;%PATH%
  - SET PKG_CONFIG_PATH=C:\msys64\mingw64\lib\pkgconfig
  - SET XDG_DATA_DIRS=C:\msys64\mingw64\share
  - cabal --version
  - appveyor-retry pacman -S -q --noconfirm mingw64/mingw-w64-x86_64-SDL2 mingw64/mingw-w64-x86_64-SDL2_ttf
  - cabal %CABOPTS% update
  - cabal %CABOPTS% install happy
  - git clone -q --branch=master https://github.com/haskell-game/sdl2
  - cd sdl2
  - cabal %CABOPTS% install -fno-linear
  - cd ..
  - git clone -q --branch=master https://github.com/LambdaHack/LambdaHack.git
  - cd LambdaHack
  - appveyor-retry cabal %CABOPTS% install --disable-library-profiling --disable-profiling --disable-documentation -f-release
  - cd ..

  - pwd
  - appveyor-retry make build-binary-common
  - cp /c/msys64/mingw64/bin/zlib1.dll AllureOfTheStars
  - cp /c/msys64/mingw64/bin/SDL2.dll AllureOfTheStars
  - cp /c/msys64/mingw64/bin/SDL2_ttf.dll AllureOfTheStars
  - cp /c/msys64/mingw64/bin/libfreetype-6.dll AllureOfTheStars
  - cp /c/msys64/mingw64/bin/libgcc_s_seh-1.dll AllureOfTheStars
  - cp /c/msys64/mingw64/bin/libbz2-1.dll AllureOfTheStars
  - cp /c/msys64/mingw64/bin/libpng16-16.dll AllureOfTheStars
  - cp /c/msys64/mingw64/bin/libwinpthread-1.dll AllureOfTheStars
  - cp /c/msys64/mingw64/bin/libharfbuzz-0.dll AllureOfTheStars
  - cp /c/msys64/mingw64/bin/libglib-2.0-0.dll AllureOfTheStars
  - cp /c/msys64/mingw64/bin/libgraphite2.dll AllureOfTheStars
  - cp /c/msys64/mingw64/bin/libintl-8.dll AllureOfTheStars
  - cp /c/msys64/mingw64/bin/libpcre-1.dll AllureOfTheStars
  - cp /c/msys64/mingw64/bin/libstdc++-6.dll AllureOfTheStars
  - cp /c/msys64/mingw64/bin/libiconv-2.dll AllureOfTheStars
  - cp AllureOfTheStarsInstall/msys64/bin/Allure.exe AllureOfTheStars
  - make version
  - SET /p LH_VERSION=<%APPDATA%\Allure\stdout.txt
  - 7z a -ssc -tzip Allure_dev_windows-x86_64.zip AllureOfTheStars
  - ps: $env:TIME_STRING=(get-date -UFormat "%Y-%m-%d").ToString()
  - ps: Push-AppveyorArtifact Allure_dev_windows-x86_64.zip -FileName "Allure_$($env:LH_VERSION)-dev-$($env:TIME_STRING)_windows-x86_64.zip" -DeploymentName "win64 binaries archive"

  - appveyor-retry cabal %CABOPTS% test --show-details=direct
#  - make test-short || (tail -n 500 %APPDATA%\Allure\stdout.txt; tail -n 500 %APPDATA%\Allure\stderr.txt; exit 77)
  - make nativeBench || (tail -n 500 %APPDATA%\Allure\stdout.txt; tail -n 500 %APPDATA%\Allure\stderr.txt; exit 77)

  - mv AllureOfTheStars AllureOfTheStars64
  - rm -rf AllureOfTheStarsInstall
  - cabal %CABOPTS% clean
  - cd sdl2
  - cabal %CABOPTS% clean
  - cd ..
  - cd LambdaHack
  - cabal %CABOPTS% clean
  - cd ..

  - appveyor-retry choco install --force --forcex86 ghc --version 8.4.4 | grep -v '^Extracting '
  # breaks appveyor-retry: refreshenv
  - SET PATH=%APPDATA%\cabal\bin;C:\msys64\mingw32\bin;C:\msys64\usr\bin;C:\ProgramData\chocolatey\lib\ghc\tools\ghc-8.4.4\bin;C:\ProgramData\chocolatey\lib\cabal\tools;%PATH%
  - SET PKG_CONFIG_PATH=C:\msys64\mingw32\lib\pkgconfig
  - SET XDG_DATA_DIRS=C:\msys64\mingw32\share
  - cabal --version
  - appveyor-retry pacman -S -q --noconfirm mingw-w64-i686-SDL2 mingw-w64-i686-SDL2_ttf
  - echo "no cabal update"
  - echo "no cabal install happy"
  - echo "no git clone -q --branch=master https://github.com/haskell-game/sdl2"
  - cd sdl2
  - cabal %CABOPTS% install -fno-linear
  - cd ..
  - echo "no git clone -q --branch=master https://github.com/LambdaHack/LambdaHack.git"
  - cd LambdaHack
  - appveyor-retry cabal %CABOPTS% install --disable-library-profiling --disable-profiling --disable-documentation -f-release
  - cd ..

  - pwd
  - appveyor-retry make build-binary-common
  - cp /c/msys64/mingw32/bin/zlib1.dll AllureOfTheStars
  - cp /c/msys64/mingw32/bin/SDL2.dll AllureOfTheStars
  - cp /c/msys64/mingw32/bin/SDL2_ttf.dll AllureOfTheStars
  - cp /c/msys64/mingw32/bin/libfreetype-6.dll AllureOfTheStars
  - cp /c/msys64/mingw32/bin/libgcc_s_dw2-1.dll AllureOfTheStars
  - cp /c/msys64/mingw32/bin/libbz2-1.dll AllureOfTheStars
  - cp /c/msys64/mingw32/bin/libpng16-16.dll AllureOfTheStars
  - cp /c/msys64/mingw32/bin/libwinpthread-1.dll AllureOfTheStars
  - cp /c/msys64/mingw32/bin/libharfbuzz-0.dll AllureOfTheStars
  - cp /c/msys64/mingw32/bin/libglib-2.0-0.dll AllureOfTheStars
  - cp /c/msys64/mingw32/bin/libgraphite2.dll AllureOfTheStars
  - cp /c/msys64/mingw32/bin/libintl-8.dll AllureOfTheStars
  - cp /c/msys64/mingw32/bin/libpcre-1.dll AllureOfTheStars
  - cp /c/msys64/mingw32/bin/libstdc++-6.dll AllureOfTheStars
  - cp /c/msys64/mingw32/bin/libiconv-2.dll AllureOfTheStars
  - cp AllureOfTheStarsInstall/msys64/bin/Allure.exe AllureOfTheStars
  - 7z a -ssc -tzip Allure_dev_windows-i686.zip AllureOfTheStars
  - ps: Push-AppveyorArtifact Allure_dev_windows-i686.zip -FileName "Allure_$($env:LH_VERSION)-dev-$($env:TIME_STRING)_windows-i686.zip" -DeploymentName "win32 binaries archive"

  - appveyor-retry cabal %CABOPTS% test --show-details=direct
  - make benchNull || (tail -n 500 %APPDATA%\Allure\stdout.txt; tail -n 500 %APPDATA%\Allure\stderr.txt; exit 77)

  - mv AllureOfTheStars AllureOfTheStars32
  - ps: '& "C:\Program Files (x86)\NSIS\makensis.exe" .windows.installer.nsi'
  - ps: Push-AppveyorArtifact Allure_dev_windows-installer.exe -FileName "Allure_$($env:LH_VERSION)-dev-$($env:TIME_STRING)_windows-installer.exe" -DeploymentName "win64 and win32 installer"

build: off
