install:
  - SET PATH=%APPDATA%\cabal\bin;C:\msys64\mingw32\bin;C:\msys64\usr\bin;C:\ProgramData\chocolatey\lib\ghc\tools\ghc-8.0.2\bin;C:\ProgramData\chocolatey\lib\cabal\tools;%PATH%
  - SET PKG_CONFIG_PATH=C:\msys64\mingw32\lib\pkgconfig
  - SET XDG_DATA_DIRS=C:\msys64\mingw32\share
  - pacman --version
  - appveyor-retry choco install --forcex86 ghc --version 8.0.2 | grep -v '^Extracting '
  - cabal --version
  - appveyor-retry pacman -S -q --noconfirm mingw-w64-i686-SDL2 mingw-w64-i686-SDL2_ttf
  - cabal update
  - cabal install happy
  - pwd
  - git clone -q --branch=master https://github.com/Mikolaj/sdl2.git
  - cd sdl2
  - cabal install
  - cd ..
# instead of the Hackage package sdl2-ttf that struggle with UTF8 fonts, at least under Wine:
  - git clone -q --branch=master https://github.com/Mikolaj/sdl2-ttf-1.git
  - cd sdl2-ttf-1
  - cabal install
  - cd ..
  - git clone -q --branch=master https://github.com/LambdaHack/LambdaHack.git
  - cd LambdaHack
  - cabal install --disable-library-profiling --disable-profiling --disable-documentation -f-release --only-dependencies
  - cabal configure --disable-library-profiling --disable-profiling -f-release --datadir=. --datasubdir=.
  - cabal build
  - cabal register --inplace
  - cd ..

build_script:
  - pwd
  - make build-binary-common
  - cp /c/msys64/mingw32/bin/zlib1.dll AllureOfTheStars
  - cp /c/msys64/mingw32/bin/SDL2.dll AllureOfTheStars
  - cp /c/msys64/mingw32/bin/SDL2_ttf.dll AllureOfTheStars
  - cp /c/msys64/mingw32/bin/libfreetype-6.dll AllureOfTheStars
  - cp /c/msys64/mingw32/bin/libgcc_s_dw2-1.dll AllureOfTheStars
  - cp /c/msys64/mingw32/bin/libbz2-1.dll AllureOfTheStars
  - cp /c/msys64/mingw32/bin/libpng16-16.dll AllureOfTheStars
  - cp /c/msys64/mingw32/bin/libwinpthread-1.dll AllureOfTheStars
  - cp /c/msys64/mingw32/bin/libharfbuzz-0.dll AllureOfTheStars
  - cp /c/msys64/mingw32/bin/libglib-2.0-0.dll AllureOfTheStars
  - cp /c/msys64/mingw32/bin/libgraphite2.dll AllureOfTheStars
  - cp /c/msys64/mingw32/bin/libintl-8.dll AllureOfTheStars
  - cp /c/msys64/mingw32/bin/libpcre-1.dll AllureOfTheStars
  - cp /c/msys64/mingw32/bin/libstdc++-6.dll AllureOfTheStars
  - cp /c/msys64/mingw32/bin/libiconv-2.dll AllureOfTheStars
  - cp AllureOfTheStarsInstall/msys64/bin/Allure.exe AllureOfTheStars
  - 7z a -ssc -sfx Allure_windows-i686.exe AllureOfTheStars
  - make test

artifacts:
  - path: Allure_windows-i686.exe
    name: win32 binaries
