resolver: lts-9.8

packages: ['.']

extra-deps:
- LambdaHack-0.6.2.0
- assert-failure-0.1.2.2
- hsini-0.5.1.1
- miniutter-0.4.6.0
- minimorph-0.1.6.1
- sdl2-ttf-2.0.1

flags: {}
extra-package-dbs: []
